### ISSUE TITLE
Duplicate Handling

### ISSUE THREAD

**Issue by livejamie** [lemasato/POE-Trades-Companion#100]
Used this a lot over the weekend to sell a bunch of maps in bulk. Was getting spammed with ~30 whispers at a time.

It would be nice if there was some sort of visual indicator or warning for when you've invited multiple people for the same item, or if you're inviting somebody for an item you just sold.

There were a couple times I invited people for maps I didn't have just trying to keep up with the incoming volume.

Thanks so much for your tool!

**Comment by livejamie** [comment]
It would be nice to set things to close similar trades when I kick somebody from one of my "kick" or "thank" buttons.

**Comment by lemasato** [comment]
?  
Sorry, I'm not quite sure to understand.  
Would you like to see "Close similar tabs" added as an action?

**Comment by livejamie** [comment]
Yeah

**Comment by lemasato** [comment]
Wondering about this issue, should it be closed?  
We now have actions to ignore items for 10mins. Closing similar tabs will be added as action in the next version.
In this case, you could sell maps and when you run out of stock, use a button that has both of these, so that you don't get any new notifications for a while and any remaining tab for the same item would be closed.

**Comment by livejamie** [comment]
Sounds good to me, thanks!
