### ISSUE TITLE
Error: expecting JSON value

### ISSUE THREAD

**Issue by Jebroer** [lemasato/POE-Trades-Companion#101]
Hi,

Since this morning I get this beautiful error when I try to launch the companion

![image](https://user-images.githubusercontent.com/38029945/38233662-96d01d08-371b-11e8-9c4e-4d456ec17321.png)

I already redownloaded the app, deleted all the files in the Autohotkey folder (preferences saved ofc ;-) ) and I also updated AHK to the latest release. Any ideas?

Thnx in advance!

**Comment by lemasato** [comment]
Hey there,

It's an issue with one of the JSON files.
In my opinion, it's either related to GitHub API or the Leagues API calls.

Could you include your logs folder?
\Documents\AutoHotkey\POE Trades Companion\Logs

**Comment by Jebroer** [comment]
Ofc, here are the logs. I don't think you need the changelogs so I left those out ^_^

[2018-04-03_08-44-46.txt](https://github.com/lemasato/POE-Trades-Companion/files/1872975/2018-04-03_08-44-46.txt)
[2018-04-03_08-46-41.txt](https://github.com/lemasato/POE-Trades-Companion/files/1872976/2018-04-03_08-46-41.txt)
[2018-04-03_08-52-11.txt](https://github.com/lemasato/POE-Trades-Companion/files/1872977/2018-04-03_08-52-11.txt)

**Comment by lemasato** [comment]
Yeah, they're empty as I was expecting.

Could you try this?:
- Download the latest source: [here](https://github.com/lemasato/POE-Trades-Companion/archive/1.12.3.zip)
- Extract it, and open Debug.json with any text editor.
- Change the `false` value for `no_online_check` to `true`
- Save your changes and run POE Trades Companion.ahk

Does the script run without any error?
If you do not get any error:
- Right click on the tray icon, and choose "About?"
- Click on the "Check Update" button.
- The GUI should disappear for a brief moment. Did you get any error?

**Comment by Jebroer** [comment]
In both cases no errors! Lost the customisation, but that's no biggie. Life was already getting hard playing without it. Thanks a lot!

**Comment by lemasato** [comment]
If you keep it like this, you will not receive a notification if an update is available.
Though, you can still manually check for update from the "About?" tray menu.

But most importantly, since the leagues are not retrieved from the API, the whispers will not be parsed correctly, and may appear incorrect on the Trades GUI.

Are you able to load up http://api.pathofexile.com/leagues?type=main&compact=1 just fine?
<details>
  <summary>Leagues API, Firefox (preview)</summary>
 <img src="https://user-images.githubusercontent.com/14184969/38274664-b59f755c-378f-11e8-9f76-de65b1ec2ede.png">
</details>

I've uploaded a version that will show a message box when calling the Leagues API:
https://ufile.io/qwgoz - Could you try it out and show me the box?

**Comment by Jebroer** [comment]
API loads fine, both in my browser and with your 'messagebox version':

![image](https://user-images.githubusercontent.com/38029945/38276395-2a0ef62e-3795-11e8-929b-e13e55660dab.png)

**Comment by Jebroer** [comment]
No error, it loaded as it is supposed to.

**Comment by lemasato** [comment]
What if you try with the executable you usually use?
Does it work normally now?
If this one works just fine, then the usual executable should too.

**Comment by lemasato** [comment]
Must have been a net communication error, that's fixed itself.
Sorry I had you going through all this trouble.

Thank you, and happy trading!
