### ISSUE TITLE
Add to controlled access in windows 10?

### ISSUE THREAD

**Issue by Deathangel908** [lemasato/POE-Trades-Companion#104]
Windows 10 blocks access to `%userprofile%\Documents\PoE-TradeMacro`. So poe-trades-companion doesn't work at all, it gives an alert that the access has ben blocked. 

I have added poe_trade_companion to list of exclusions but it uses other scripts that are accessing this directoring, e.g.  `wscript.exe`. How do people usually solve this issue? 

 - I don't wanna turn off controlled acess
 - I don't wanna add 100 programs to exlusing just because `POE-Trades-Companion` uses them.
 - I don't wanna exclude Documents directory from controlled access
 - Maybe windows 10 allows to skip subdirectory from exlusion but I didn't find it...

How this even happens, am I the only one who's using windows 10?

![image](https://user-images.githubusercontent.com/1336703/39388152-a29ce03e-4a86-11e8-8d18-6b302160f261.png)

**Comment by lemasato** [comment]
I never used this "Controlled Access" thing, but can't you simply add `Documents\AutoHotkey\POE Trades Companion` as an exception for POE Trades Companion (and WScript.exe to an extent)?
This is the only folder we make changes to.

WScript is a command used by a .vbs script to retrieve a list of the fonts installed.

**Comment by Deathangel908** [comment]
>  but can't you simply add Documents\AutoHotkey\POE Trades Companion as an exception for POE Trades Companion (and WScript.exe to an extent)?
That's what I did, but other folks who would use the app may expirience the same issue won't be able find a way how to resolve it. 

Does `POE-Trades-Companion` executable installs those font, or those are preinstalled OS fonts? If it's our fonts is there an option we get fonts w/o `wscript`?

**Comment by lemasato** [comment]
To be honest, I don't think that regular users would be using W10 Controlled Access.  
So if anyone does in fact use it, it's likely that they will find a way to make it work (just like you did).

Actually, the external .vbs script does not install fonts. It is used to retrieve the exact count of fonts installed. This number is necessary because once you reach 701 fonts installed, it takes significantly more time to draw the GUI (and so, we warn the user about it).  
The .vbs script is the most reliable way I found to retrieve this number, sadly there isn't any way around it.
