### ISSUE TITLE
launch error 0x80004001 Specifically: GetDetaildOf Line# 4734

### ISSUE THREAD

**Issue by MrSamoylov** [lemasato/POE-Trades-Companion#114]
Run from .exe
Error: 0x80004001
Specifically: GetDetaildOf
Line# 4734: if (PropName := oFolder.GetDetailsOf (0,A_Index -1))

0114:fixme:shell:FolderImpl_GetDetailsOf (0x1840f0,0xe5add0 {VT_I4: 0},9,0xe5af90)

Run from .ahk
Minimize: Specified font family is empty!
....
Button Custom 5: Specified font family is empty!

What fonts did you use?

P.S. I run it under wine.

**Comment by lemasato** [comment]
All fonts used are extracted in `Documents\AutoHotkey\POE Trades Companion\Fonts`, but installing them will not help as they are now used as a private fonts since 1.12.5.

Seems FGP_Init() (part of the [FileGetProperties](https://autohotkey.com/boards/viewtopic.php?f=6&t=3806) library by Kon) can't run correctly, most likely due to how Wine works. Sadly can't help you on this one, so I'd recommend you to seek help with the Wine community to see if there is anything you can do.

In case it could help, here are the FGP functions used:
FGP_Value is used to retrieve the font files' title.
Your error appears during FGP_Init, which prevents from retrieving the titles from the .ttf files.
```
FGP_Init() {
	static PropTable
	if (!PropTable) {
		PropTable := {Name: {}, Num: {}}, Gap := 0
		oShell := ComObjCreate("Shell.Application")
		oFolder := oShell.NameSpace(0)
		while (Gap < 11)
			if (PropName := oFolder.GetDetailsOf(0, A_Index - 1)) {
				PropTable.Name[PropName] := A_Index - 1
				PropTable.Num[A_Index - 1] := PropName
				Gap := 0
			}
			else
				Gap++
	}
	return PropTable
}

FGP_Value(FilePath, Property) {
	static PropTable := FGP_Init()
	if ((PropNum := PropTable.Name[Property] != "" ? PropTable.Name[Property]
	: PropTable.Num[Property] ? Property : "") != "") {
		SplitPath, FilePath, FileName, DirPath
		oShell := ComObjCreate("Shell.Application")
		oFolder := oShell.NameSpace(DirPath)
		oFolderItem := oFolder.ParseName(FileName)
		if (PropVal := oFolder.GetDetailsOf(oFolderItem, PropNum))
			return PropVal
		return 0
	}
	return -1
}
```

**Comment by MrSamoylov** [comment]
I disable LoadFonts() and some install script line 7024, cuz it search AutoHotkey in "My Documents".
So I don't have "My Documents".
Maybe better use %A_AhkPath% or %A_ScriptDir%
Same as PoE-TradMacro project.

**Comment by lemasato** [comment]
Actually, if it's only because of that, you could very easily make the changes.

There is two methods. 
The first (and easy) one is to use Cmdline parameters.

1. Create a folder "POE Trades Companion"
1. Download the latest release executable and put it in that folder.
1. Copy your production_Config.ini (file that stores all of Path of Exile settings) in there as well.
1. Make a shortcut of POE Trades Companion.exe and add following parameters:
`/MyDocuments="Path/To/POE Trades Companion"`
This parameter allows to effectively use the specified location instead of /Documents/
`/GameINI="Path/To/POE Trades Companion/production_Config.ini"`
This one allows to specify the location of the production_Config.ini, which is required to read your chat key.
1. Run the shortcut.
If the issue was because of the MyDocuments location, the tool should now work as intended.

I'm not sure how cmdline parameters can be added on unix os or if shortcuts can be created at all, so adapt these steps to your OS.
***
The other method is to edit the .ahk source:

1. Create a folder "POE Trades Companion"
1. Download the latest source zip and extract it in that folder.
1. Open POE Trades Companion.ahk and make the following changes:
1. At line 88
replace `ProgramValues.Local_Folder := MyDocuments "\AutoHotkey\" ProgramValues.Name`
with `ProgramValues.Local_Folder := A_ScriptDir "\Documents\AutoHotKey\" ProgramValues.Name`
1. At line 103:
replace `ProgramValues.Game_Folder := MyDocuments "\my games\Path of Exile"`
with `ProgramValues.Game_Folder := A_ScriptDir "\Documents\my games\Path of Exile"`
1. Save your changes and run the script once, so all folder/subfolders are created, then close the tool.

Now you need a production_Config.ini. This is where Path of Exile stores all your options.
We use it to retrieve your chat key, in case it has been changed from default (Enter).
Copy it inside your `\POE Trades Companion\Documents\my games\Path of Exile\` folder.

You should now be able to run the tool normally. All files will be extracted inside your newly created POE Trades Companion folder.
