### ISSUE TITLE
Trojan Horse Detected

### ISSUE THREAD

**Issue by Liamswin01** [lemasato/POE-Trades-Companion#117]
When trying to download and install the companion, I get multiple notifications from my anti viruses + windows defender, that there is a Trojan Horse embedded in the code/files of this, could someone verify or help me with this?

**Comment by lemasato** [comment]
Could you post a screenshot of the message?
Just want to make sure it's specifically saying that the executable is infected or if it's just implying it's unsafe because it wasn't signed by Microsoft.

[Virustotal.com scan of the latest release](https://www.virustotal.com/#/file/86beff27332af9bfeead656de3684ff2accdd40d304fb0aabd9594808bce10c8/detection)
No major positive results. Also, in my experience, some antivirus will even flag an empty AHK script that has been compilled. This behaviour usually changes based on the AHK version used.

Personally scanned the executable with WinDefender, no positive results.  
Additionally, you may want to look at this #52 

If you are still getting the issue, you may want to add the program as exclusive.  
In case you feel unsafe, you may want to use the source code instead, [it's very simple](https://github.com/lemasato/POE-Trades-Companion/wiki/Usage). The only downside is that you will have to update manually if you still wish to keep using the source.

**Comment by Liamswin01** [comment]
Hi thanks for the quick response, it's no longer saying "Trojan" in the file that is suspected to have to virus, but I can provide some ss's of the warning I get from the anti-virus.

https://prnt.sc/k3c6by
https://prnt.sc/k3c6h8

**Comment by lemasato** [comment]
Here's an example. The script was a new one, freshly created: [virustotal.com](https://www.virustotal.com/fr/file/ac60cffd7623c2e65a383eec9ad21ceed8e195282384ef55e11831870030508e/analysis/1530888247/).
Ransomware detected by McAfee (lol). Some protections just don't like compiled ahk script.

I just downloaded the executable from Chrome. No issues.
Found [this article by Microsoft](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Adware:Win32/Unwaders.D!ml&ThreatID=242864) about Unwaders.D!ml. It's talking about an adware. I'm not sure but could your browser have been infected? You could give [AdwCleaner by MalwareBytes](https://www.malwarebytes.com/adwcleaner/) a go to make sure.

**Comment by Liamswin01** [comment]
Hmm will try it, thanks for the info, will keep you informed on what happens :D

**Comment by Liamswin01** [comment]
Okay, so I just tried deleting everything to do with my browser, and installing it again, tried to anti virus and even tried just download the source code and then got this in windows defender? http://prntscr.com/k3cwud

**Comment by lemasato** [comment]
Could you compare the downloaded file hash?  
1. Create a new folder "hash" at the root of your disk (eg: C:)
1. Download the latest executable [from here](https://github.com/lemasato/POE-Trades-Companion/releases/latest)
1. Move the executable to the folder we created (eg: C:/hash)
1. Open a command prompt (Win+R, type in "cmd")
1. Inside the command prompt, type in:
`powershell`
`c:`
`cd c:/hash`
`get-filehash ".\POE Trades Companion.exe"`

1. Compare the SHA256 hash. It should be:
`86BEFF27332AF9BFEEAD656DE3684FF2ACCDD40D304FB0AABD9594808BCE10C8`
If it is, then you are entirely safe to use the executable.
***
> http://prntscr.com/k3cwud

Which file is triggering the positive? (Click on the "V", then "See details")
The source includes the executables (POE Trades Companion.exe, Updater.exe, Updater_v2.exe), so it's most likely one of these. If so, you can just delete them if you wish to use the ahk source.

**Comment by Liamswin01** [comment]
it says that it's POE-Trades-Companion-1.12.5.zip. but when I follow the file path, I have no files, anywhere on my computer to delete...

**Comment by lemasato** [comment]
Yeah it's because the file is put into quarantine.  
I have uploaded the .zip source without POE Trades Companion.exe, this should allow you to download it.

But you really should do the hash comparison stuff. Just make sure to disable WinDefender before downloading the file to make sure it doesn't interfere.  
If the hash is different, this will confirm that your browser modifies the file in some way.
If it's clean, that'll means you're good to go and whitelist it in WinDefender.

[POE-Trades-Companion-1.12.5_noPOETCexe.zip](https://github.com/lemasato/POE-Trades-Companion/files/2171635/POE-Trades-Companion-1.12.5_noPOETCexe.zip)

**Comment by Liamswin01** [comment]
http://prntscr.com/k3fhji

I followed the instructions you gave me with the cmd thing and this happened.

**Comment by lemasato** [comment]
Says the path doesn't exist.
Did you put POE Trades Companion.exe into c:/hash?

**Comment by Liamswin01** [comment]
when you say "Create a new folder "hash" at the root of your disk (eg: C:)" do you literally just mean create a folder called hash?

**Comment by lemasato** [comment]
Yup

**Comment by Liamswin01** [comment]
okay, so I went into my C: disk, which is an M.2 drive which wouldn't make a difference right? and made a folder called hash, then downloaded the file you provided, dragged that folder into the hash folder, went into cmd and typed "powershell" "c:" "cd c:/hash" "get-filehash ".\POE Trades Companion.exe""

**Comment by lemasato** [comment]
Weird... It's like the file doesn't exist at all.
Are you sure the file is in the hash subfolder?
If so, double-check that nothing is "blocking" it (antivirus, etc)

**Comment by Liamswin01** [comment]
http://prntscr.com/k3fpn7
http://prntscr.com/k3fpq0
http://prntscr.com/k3fq45

**Comment by lemasato** [comment]
Ah, you created a folder named POETC.exe.  
You actually need to [download](https://github.com/lemasato/POE-Trades-Companion/releases/latest) `POE Trades Companion.exe` and put it in there.

**Comment by Liamswin01** [comment]
ahhhh okay lmao xD

**Comment by Liamswin01** [comment]
http://prntscr.com/k3frzt

**Comment by lemasato** [comment]
So I made a small .ps1 script that will list the hash of all files in its folder.
Just make sure to drop your downloaded POE Trades Companion.exe in there aswell.

[hash.zip](https://github.com/lemasato/POE-Trades-Companion/files/2171760/hash.zip)

**Comment by lemasato** [comment]
So I made a small .ps1 script that will list the hash of all files in its folder.
Right click on sha256.ps1 and choose "Run with Powershell"
Just make sure to drop your downloaded POE Trades Companion.exe in there aswell.


[hash.zip](https://github.com/lemasato/POE-Trades-Companion/files/2171760/hash.zip)

**Comment by Liamswin01** [comment]
I'm guessing I just put that into the c: drive where my previous folder was?

**Comment by lemasato** [comment]
It'll work no matter where it is.

**Comment by Liamswin01** [comment]
when I right click it, it doesn't give me that option

**Comment by Liamswin01** [comment]
it's also asking for a password to access the file?

**Comment by lemasato** [comment]
Oh yeah, forgot to mention that my bad. Password is `0000`
You need to extract the archive prior. Then right click on sha256.ps1

![screenshot](https://i.imgur.com/XHAZzLb.png)

**Comment by Liamswin01** [comment]
okay, so I did that and I have two?

**Comment by Liamswin01** [comment]
http://prntscr.com/k3g2l0

**Comment by lemasato** [comment]
Yeah those are the hashes of the files pre-included in the archive.
But you still need to add in the downloaded POE Trades Companion.exe.

[Direct download link](https://github.com/lemasato/POE-Trades-Companion/releases/download/1.12.5/POE-Trades-Companion.exe)
Download and put in together with the sha256.ps1 and TradesCompanion_Original.exe

**Comment by Liamswin01** [comment]
https://prnt.sc/k3g3zy so with all 3 being shown now, does this mean that something within my browser or antivirus is changing the file?

**Comment by lemasato** [comment]
Seems like it to me.  
Try and upload it to [virustotal.com](https://www.virustotal.com/#/home/upload) to see.

**Comment by Liamswin01** [comment]
https://www.virustotal.com/#/file/75e481fb80a1a2c73161703ba31115d075c7389d7787f738a8122e900cfdd72b/detection

**Comment by Liamswin01** [comment]
what would I do with this information now?

**Comment by Liamswin01** [comment]
uhmmm, 9/68 detected the file as having a virus.

**Comment by lemasato** [comment]
Actually reffering to [post#403058140](https://github.com/lemasato/POE-Trades-Companion/issues/117#issuecomment-403058140), where I talked about AdwCleaner, not the virustotal scan.  
If you did not ran AdwCleaner, you really should start by that.

**Comment by Liamswin01** [comment]
I just ran that and it got rid of the companion file and made me restart my computer, is there anything I can do now?

**Comment by lemasato** [comment]
Redo the same steps again (download exe, put in folder, run sha256.ps1), to compare the hash.
If it's still different, you need further cleaning.

**Comment by Liamswin01** [comment]
it's still different I'll just have to reinstall, safer option on my end and get's my computer running at optimal speeds again without all this shit in it lmao

**Comment by lemasato** [comment]
If you're fine with reinstalling, yeah that should work.  
Beware that if you have more than one partition, or decide to do an upgrade installation (which keeps a Windows.old folder) infected files will remain in their places.  

I personally usually follow [this guide](https://malwaretips.com/threads/how-to-remove-trojans-spyware-rogues-and-other-malware.6941/) or just run [TronScript](https://www.reddit.com/r/TronScript) ([ddl](https://bmrf.org/repos/tron/Tron%20v10.5.2%20(2018-07-04).exe))
In your case, it could actually still be good to run TronScript to avoid the hassle of reinstall.
Just gotta reboot in safemode+network and let it run for the night.

**Comment by Liamswin01** [comment]
how do I reboot in safemode and what does "+network" mean xD I don't know what anything means when it comes to stuff like that xD

**Comment by Liamswin01** [comment]
nvm, I get what I have to do now

**Comment by lemasato** [comment]
TronScript usually takes hours.
I don't recommend on running it now unless you don't plan on using the computer for a good while.

**Comment by lemasato** [comment]
Hey there, so apparently, I messed up...
Your downloaded file was just fine. My GitHub folder was based on a different branch, and I was comparing the hash to that branch's file instead of the master branch. So, obviously, it was different.

I'm sorry you had to do all of this, when in fact, there was nothing wrong from the start.
But in the end, it's all fine. The file is not infected. It's just antivirus being silly against AHK scripts... Usually I just ignore the positives, as they're always from low-tier antivirus. But when even WinDefender flags the file, that becomes extremely annoying.

I also have (what appears to be) a "bad habit" of always keeping my AHK version up to date. And this can cause some antivirus to flag the file while it would have been fine on the older version.
Here's an example. This is the 1.12.6 executable. 
One compiled on [1.1.28.02](https://www.virustotal.com/#/file/39f648326add98b1429c8604ae820df35aac5e6f217534e0b34c3d5e4350d001) (3 flags) and the other on [1.1.29.01](https://www.virustotal.com/#/file/e4e6ec51f1bd11edfca50059f657d97c1fb57614424580ce20452ab11c4af9ab) (5 flags)
As we can see, the version build on 1.1.28.02 gets less warning than the one on 1.1.29.01

To go even further, those are the same files, but without their description/version changed: [1.1.28.02](https://www.virustotal.com/#/file/f738b0f4ecd43caac91ef8a8470f58c9329602eb75568f77f512bbeda4646dcb) and [1.1.29.01](https://www.virustotal.com/#/file/3fd9fcd1bdd0a79799f029f3a917b4db243f6b76e953df6b4272b613cf989fc3). The first one gained one flag, while the second remained the same. Even the slightest change can give different results.

All those flagging issues would be gone if I were to stop using compiled executable, but having a single portable exe (instead of a whole folder with multiple files) that you can put anywhere is just sooo convenient in my opinion...

So yeah.  
Your executable as posted on [comment#403134618](https://github.com/lemasato/POE-Trades-Companion/issues/117#issuecomment-403134618) was fine. I know those positive flags are scary (and they are just as much of an annoyance to me), but that's something I have to deal with as a dev that choose AHK.

I truly apologize for all the time this took, needlessly. Still hoping you learned a thing or two, to make it up...

**Comment by Liamswin01** [comment]
Don't worry about it haha, you gave me some useful information in any case that has helped me, but with what you're saying is I more than likely don't have a virus on my computer, it was just that anti viruses, such as windows defender just don't like ahk?

**Comment by lemasato** [comment]
Yep. Some antivirus don't like compiled AHK scripts.
Usually WinDefender doesn't flag those, but sometimes it happens.

If you don't have it already, I'd recommend getting [MBAM](https://www.malwarebytes.com). It's a nice free addition to any antivirus you may use. Past the 15days PRO trial, just run a manual scan once in a while (every week or every two week is fine) and you're good to go.

**Comment by Liamswin01** [comment]
Okay, thanks for taking the time to help me with the noobiness of not understanding shit haha. I will try MBAM when I have chance to download it
