### ISSUE TITLE
File Blocked by Symantec

### ISSUE THREAD

**Issue by Ron44** [lemasato/POE-Trades-Companion#121]
Hi,

The macro is being blocked by Symantec. Might need to look into it as it is showing as Trojan.

**Comment by lemasato** [comment]
[Virustotal: 21/65](https://www.virustotal.com/#/file/3fb492ba8acb581e98ad137960e0e63871d57bdd8c19552d2f4c1c13a42a648d/detection)
God, what even is happening...

I can understand NSO Manager getting flagged due to VirtualBox, but this never happened on Trades Companion. It's really getting annoying...

If you don't wish to add it to exclusions (which I can understand) I'd recommend disabling your antivirus, download the source zip, extract, delete the executable, re-enable your antivirus.
Then just run POE Trades Companion.ahk

I'm really getting tired of compiled ahk scripts getting flagged. If that continues, I'll have to resort using source only, which I don't want to... Having a single .exe is just too convenient.

**Comment by lemasato** [comment]
Looking at the [PayloadSecurity comment](https://www.virustotal.com/#/file/3fb492ba8acb581e98ad137960e0e63871d57bdd8c19552d2f4c1c13a42a648d/community), I see it's talking about with the .vbs script used to get the fonts count, and some skin .png assets getting extracted... which is just ridiculous.

**Comment by deduijk** [comment]
Hey, 
Seeing the same thing on g-data; trojan is being reported since version 1.12.5.
1.12.4 doesn't register as containing a trojan.

Could be false-positive, i see u added some font stuff. Anything to do with fonts is always considered a high risk to begin with these days.

I hope you could compile one without. Never had an issue with fonts in TC, so i doubt for me it will result in issues. I don't know about others of course.. , but maybe split branches if you feel the font feature is needed?

**Comment by lemasato** [comment]
The font stuff  is pretty important to me.
Back then, fonts needed to be installed onto your system for Trades Companion to use them. This was leading to some complicated issues when having to update your local font in the /Windows/Fonts folder with the new version provided by the tool (due to adding a new character to TC_Symbols for example).
Now, they can be loaded into the memory so that only Trades Companion has access to them. This makes it way easier as we can simply replace the font file in Trades Companion's local folder (/Documents/AutoHotkey/POE Trades Companion).

I don't think the recent flagging is related to that.
I re-compiled the executable including the [latest commit](https://github.com/lemasato/POE-Trades-Companion/commit/63a3b29f56435d12f0cd5105560d125d3367ea35), and [it instantly drops to 7/67](https://www.virustotal.com/#/file/8748f7169c19a0767fdedcbdaae84c5509faf5936bbc76ebe9e3d46337e55c0f/details). Even though there was only a single line change, the most important positive flags disappeared.
I'll have to check it again later, in case that changes for the worst...

I'm sure you guys trust me, but I'll say it again: I don't include malware in my projects.
And just to make sure, I re-compiled the executable on a clean virtual machine... got the same results as [on this post](https://github.com/lemasato/POE-Trades-Companion/issues/121#issuecomment-408679484), so it's definitely not my computer being funny either.
I know from personal experience that AHK executable can get lot of hate from virus scans, and it's really annoying me as much as you.

I'll be waiting a few hours then check the 7/67 scan again. If it doesn't change, I'll be pushing it as release as a temporary fix. I'll be properly inspecting what could be causing these flags once 1.13 betas are released, as it brings a lot of changes code-wise and so it would be a waste of time to inspect now.

**Comment by Pfedza** [comment]
Windows Defender on W10 just flagged it for a trojan as well.

**Comment by argosreality** [comment]
![poe_tradecompanion_vr](https://user-images.githubusercontent.com/41969396/43479000-62898dd0-94cd-11e8-9acb-e411c00f96c6.JPG) Can confirm Windows Defender blocks as Tilken.B!cl

**Comment by lemasato** [comment]
RIP.
Pushing the update.
Let's hope it fixes it temporarily.

**Comment by lemasato** [comment]
[Virustotal for 1.12.7 - 4/66](https://www.virustotal.com/#/file/87d8b2170d551e0c2960a74848942f79f67a4ceac6b918a0e63d383280a5fd46/detection). Seems we're good for now.
Tried not to use VerPatch (changes the .exe infos, such as file version, description, etc), in case that could remove some flags but nope it only adds more: [6/66](https://www.virustotal.com/#/file/d1db42db7030d8850c4bd16d2fa08e83972409068a87321248f378ea077db9cf/detection)

I'm sorry this is happening. Honestly, this is really annoying to me. Could give a bad rep, and lose fans due to them being scared (which I understand) and end up using other trading tools.

Once 1.13 betas releases, if this keeps on happening, I'll resort to using zip source only.

**Comment by lemasato** [comment]
Available now: [1.12.7](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.12.7)
[Direct download](https://github.com/lemasato/POE-Trades-Companion/releases/download/1.12.7/POE-Trades-Companion.exe)

**Comment by Ron44** [comment]
Thanks man. Awesome work on this and grateful for the time and effort you
put in. Will test the new update later and let you know.

**Comment by Ron44** [comment]
Exception put in for the file. This works now.

**Comment by deduijk** [comment]
1.12.7 doesn't prompt anything for me. great work, suspect there was quite a bit of debugging/ trial n error needed.

Awesome you got it 'fixed' so fast.
I don't think any would suspect it being malware, but i agree, could give a bad rep and be a hurdle for new users.

Keep up the good work and thanks again.

**Comment by lemasato** [comment]
@deduijk To be honest, I didn't do much.
Simply changing one character will do the trick, as the resulting executable will have a different signature. This is only a temporary workaround, I don't think it can last permanently (See #122, WinDefender already flags it again).  

The only permanent solution is to... not use executables.  
I'll have to find a proper solution that uses only the .ahk source code.

**Comment by lemasato** [comment]
I opened a general post for the malicious flagging.
For any talk about the issue, please post over there.
You can find it over here: #124
