### ISSUE TITLE
Item name being send as message

### ISSUE THREAD

**Issue by Sindusk** [lemasato/POE-Trades-Companion#128]
It appears that the copied search string is being sent to the buyer instead of the /kick command. The buyer remains in the party and you end up with something like this:

[Image](https://i.imgur.com/Vx4BWRm.png)

Version 1.13.BETA_7
Default Thank You button configuration.

**Comment by EThaNol2005** [comment]
i can confirm, this happend if i used the c&p stashtab search.

**Comment by lemasato** [comment]
This is due to the clipboard being reverted "too early" (Message are sent using the clipboard).

@Sindusk @EThaNol2005 Could any of you try this executable?
I have disabled clipboard reverting.
Upon starting the executable, you will get a tab open.  
Don't worry, you can spam the buttons as much as you want. I made it so the tab cannot be closed by custom buttons, and the character name is linked to my old side-account.

[POE Trades Companion.zip](https://github.com/lemasato/POE-Trades-Companion/files/2336510/POE.Trades.Companion.zip)

**Comment by Sindusk** [comment]
Tried that version and the player would not get kicked from party, same as before. Only difference is that it wouldn't send the name of the item as a message to them.

**Comment by Sindusk** [comment]
[2018-08-30 17h26m56s.txt](https://github.com/lemasato/POE-Trades-Companion/files/2338057/2018-08-30.17h26m56s.txt)

Tried it with a few sales. The first sale worked fine up until the point where it should kick the player. It failed to kick. The second one it failed to send the "still interested" line once. After pressing it again, it sent successfully.

**Comment by lemasato** [comment]
@Sindusk Sweet. Thanks a lot for the testings. I'd like to have you test one more if you don't mind:

[TC_#128_NoReset.zip](https://github.com/lemasato/POE-Trades-Companion/files/2338096/TC_.128_NoReset.zip)

**Comment by Sindusk** [comment]
[2018-08-30 17h59m55s.txt](https://github.com/lemasato/POE-Trades-Companion/files/2338126/2018-08-30.17h59m55s.txt)

Okay so everything is working fine for the few trades I received when using it, however there was one minor issue: the item would not copy to clipboard for search in stash. This is something I can live without, but I figured I would mention it.

Also, thank you for taking the time to work on this issue, and I deeply appreciate PoE Trades Companion. Hard to think of trading again without it. 👍

**Comment by lemasato** [comment]
Sweet.  
I'll get rid of the clipboard reverting system.  

> the item would not copy to clipboard for search in stash

Yeah. This is because the clipboard is no longer reverted, and messages are sent using the clipboard.  
Ideally, you would need to have the "clipboard item infos" action as last. But I'll add a workaround that re-copies the item data after the button actions are done.

Thank you for the kind words, I really appreciate it!

**Comment by Sindusk** [comment]
Looks like it's still having some really weird interactions though. It's failing to clipboard the item after invite to party and it's also sending invalid messages when inviting players to the party. Luckily, it's still working in all functionality such as kicking and inviting. It's just the messaging that seems to be getting messed up.

**Comment by lemasato** [comment]
Yeah. I ended up adding a clipboard reset timer.  
Thought it would work out, guess it did not.  Can't really work on it today, so I'll completely remove clipboard revert/reset next update tomorrow. Sorry :/

**Comment by lemasato** [comment]
Should be good now. [1.13.2](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.13.2)  
I'll leave this open for a few days, in case it wasn't related to that.

**Comment by lemasato** [comment]
@Z0MBIE2 @Sindusk @EThaNol2005  

I have attached a zip file on this post. It contains two executable that contains some fixes.
Spam testing.exe: Upon opening, you will have a pre-open tab. The tab will be unable to be closed so that you can do all the testings you wish on it.  
POE Trades Companion.exe: The regular tool, but with the fixes included. You can trade as you normally would.

If you encounter the issue, please let me know.
Would be great to find a way to reliably reproduce it. I have tried many times but was unable to do it. But one thing for sure is that it's related to the clipboard.
Also, if you do encounter the issue, please try again but without TradeMacro running.

[POE TC - Item name being sent.zip](https://github.com/lemasato/POE-Trades-Companion/files/2361200/POE.TC.-.Item.name.being.sent.zip)

**Comment by EThaNol2005** [comment]
As short feedback: haven't seen the problem, since some versions.
if i find the time this weekend, i'll test it.

**Comment by Z0MBIE2** [comment]
Can confirm the fix seems to work great, no issues for a few dozen trades.

**Comment by lemasato** [comment]
Seems to still happen, as reported over discord.  
If you still experience the issue, please try this executable:  
https://github.com/lemasato/POE-Trades-Companion/raw/Clipboard-issues/POE%20Trades%20Companion.exe

If you'd like the source zip instead:
https://github.com/lemasato/POE-Trades-Companion/raw/Clipboard-issues/POE-Trades-Companion-Clipboard-issues.zip

- Added a 700ms wait between the last action and copying the item name.
- This timer can be adjusted to 700/1200/200 ms from the tray menu.

If you get the issue at 700ms, try a higher value.  
Report back at which value the error stopped occurring.

**Comment by Z0MBIE2** [comment]
Sorry for late reply, but both the zip and the exe are being blocked by chrome. First test works, but the other version seemed to work most of the time and only sometimes glitched, so will report if I get it again anytime in the next day.

**Comment by lemasato** [comment]
Included a 500ms timed wait before copying the item name, to make sure it doesn't replace the message that should be sent on [1.13.4](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.13.4)
