### ISSUE TITLE
Interface Transparency Not Working

### ISSUE THREAD

**Issue by Irraticate** [lemasato/POE-Trades-Companion#144]
While in game or on another window, the interface will always show like at 0 transparency, even when both sliders are set to 100. This starts happening after the first alt-tab out of Path of Exile (in both windowed, full screen and windowed full screen) after the program first launches.

I've tried:
Reinstalling (with new settings)
Running with and without Admin
Trying a combination of settings (with and without clickthrough, lock, etc)
All 3 default skins
Restoring default settings

Edit: Steps I have tried.

**Comment by rushtothesun** [comment]
I haven't had this issue, but I have seen it flickering.

**Comment by Irraticate** [comment]
I found the solution: simply reinstalling. I also chose to not copy my old settings from previous versions and this to have done the trick.

I shouldn't gone through the typical software troubleshooting steps, lol.

**Comment by Dagda47** [comment]
I also experience the same issue as sclient.

**Comment by lemasato** [comment]
@sclient There was an issue with the transparency, when "Only show while in game" was enabled. This has now been fixed as of [1.13.2](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.13.2), thanks for reporting!
&nbsp;  

About the original issue
>the interface will always show like at 0 transparency, even when both sliders are set to 100

By 0, do you mean "invisible"?
Because if I consider 0 as "visible" then your issue sounds exactly like sclient's one.
There shouldn't be any issue where the tool stays invisible, unless you have "Only show while in game" enabled and are tabbed out of the game.

**Comment by Irraticate** [comment]
Yeah, it seems that the fix you put in 1.13.2 based off of Sclient also fixed my issue. Reading back on my OP I did word it incorrectly and my issue was the same as Sclient's.

**Comment by lemasato** [comment]
Sweet, thanks for reporting!
