### ISSUE TITLE
The tool is redownloading on launch every day

### ISSUE THREAD

**Issue by rhazor** [lemasato/POE-Trades-Companion#167]
Pretty much it. Works fine, it's just a bit annoying.

**Comment by rhazor** [comment]
1.13.5 and it's executable
[Logs.zip](https://github.com/lemasato/POE-Trades-Companion/files/2487128/Logs.zip)

**Comment by lemasato** [comment]
Seems it is happening because you are running the v1.13.4 again.  
Apparently, you have two executables in that folder:  
- POE-Trades-Companion.exe, which is on v1.13.4.
The executable you originally downloaded from the releases tab.
- POE Trades Companion.exe, which is on v1.13.5.
The executable as it will be renamed after updating.

Normally, your old executable should automatically be deleted upon updating.

**Comment by rhazor** [comment]
fixed
