### ISSUE TITLE
I moved Game path and Macro doesn't work

### ISSUE THREAD

**Issue by Lockert** [lemasato/POE-Trades-Companion#184]
Hi, i recently moved the PoE gamepath to my SSD (C disk) and macro stopped reading the whispers. How can i fix this or change the macro pathing to client.txt(i tried to reinstall it but still same)? Thanks

**Comment by lemasato** [comment]
Hi, sorry for the late answer.

- Close both the game and the tool.
- Go to your game's folder and open the logs folder.
Delete the Client.txt file
- Run the game again, but make sure to start it as administrator
- Run the tool too, also as administrator
- Once in game, copy your own whisper from poe.trade and send it to yourself.
Make sure that you are sending it to your current character as it won't work otherwise
- Report back about whether the tool is now working or not
- Also make sure that a new Client.txt file has been created by the game.

**Comment by Lockert** [comment]
Thanks, it worked, seems like some weird bug with Client.txt
