### ISSUE TITLE
Item Grid Location?

### ISSUE THREAD

**Issue by gotex007** [lemasato/POE-Trades-Companion#193]
I have no idea what this feature is actually supposed to look like. I see it's supposed to have colored boxes or something, but nothing happens regarding it at all. I have it ticked to show, I've tried using the hotkey to manually make it work, and I've also just invited people to trade assuming it would work but absolutely nothing appears on the screen and I see zero indication of this feature functioning at all.

So either I'm not understanding what it's supposed to do and cannot find where any sign of this feature is appearing on my screen or it simply isn't working.

**Comment by lemasato** [comment]
Hi,  
Are you using premium stash tabs?  
This feature can only work with them, as we need the item position from the whisper.

**Comment by gotex007** [comment]
Why does it say "Works with regular stash tabs" then? You should probably specify. Is this also why the "Price check against scammers" also doesn't work?

**Comment by lemasato** [comment]
Does it? If so, I'm sorry, it's a typo from my part. Could you let me know where is that?  
Also yes, I decided not to make price checking compatible with regular tabs because you could have two items with the same name but different prices. This is especially true with unique items where roll matters, or rare jewels that can have the same name but different mods.

**Comment by lemasato** [comment]
Oh.  
```
 Works with regular stash tabs, quad stash tabs, and the map stash tab.
```

By regular stash tab, I meant the regular premium stash tab. Mistake corrected.
