### ISSUE TITLE
Trade Window doesn't show

### ISSUE THREAD

**Issue by Skreevy** [lemasato/POE-Trades-Companion#199]
The Trade Window, or any other part of the Companion do not show up as overlay on PoE. I have it started correctly (and I had it working before), and the icon is correctly in the taskbar, but the window simply doesn't show. When I (re)start or reload the Companion it shows for a fraction of a second and immediately disappears.

**Comment by lemasato** [comment]
Right click on the tray icon > Reset position.
Does it help?

**Comment by onyilam10** [comment]
Having the same problem, and no it didnt work.

**Comment by onyilam10** [comment]
Im getting a short flash of the window if i edit it or anything, but it doesnt stay.

**Comment by lemasato** [comment]
@onyilam10 The interface appears without transparency for a split second before applying transparency settings. On default, when you don't have any trading whisper, the window is made fully transparent so that it doesn't bother you while playing.

1. Does it still not appear after receiving a trading whisper?
1. Can you hear the Trades Companion notification sound when receiving a trading whisper?
1. Shouldn't help much, but can you provide your logs?
\Documents\lemasato\POE Trades Companion\Logs - Zip the folder and attach it here.

You can whisper yourself from poe.trade to trigger a notification.
Make sure that you are logged on the same character you send the whisper to.

**Comment by onyilam10** [comment]
Oh sorry then, i diddnt know. I used this app about 3 years ago and it showed up while doing settings so i was a little confused. After getting whispered i get the UI so thats great.

Seems like its working well. Thanks dude.
