### ISSUE TITLE
App resets after receiving trade message

### ISSUE THREAD

**Issue by kasprzakdanielt** [lemasato/POE-Trades-Companion#203]
Was working fine till it downloaded a new update. Now it's just closing afrter receiving trade message and then reopens few seconds later

**Comment by lemasato** [comment]
Seems to happen only with the executable.
This is due to the new automated price verify feature.

I'll push a fix immediately.

But you should really start using the AHK version instead.
In the future, the executable will disappear completely due to some av flagging stuff.
On the releases page, download POE-Trades-Companion-AHK.zip

**Comment by lemasato** [comment]
Pushed 1.14.1
> -  Fix: When using the executable version, the app would reload upon verifying an item's price.
> For this reason, the feature has been temporarily disabled for the executable version.
> #### If you are still using the exe, please switch to the AHK version instead. Simply download POE-Trades-Companion-AHK.zip from the latest release. The exe is bound to disappear completely in the future due to some stupid recurrent flagging issues.

I could fix this by compiling the new separate script that verifies an item's price and include it into the executable, but I don't think it's much of a good idea. On the next "big" update, users will most likely be automatically migrated to the AHK version, discontinuing exe support.
