### ISSUE TITLE
Typing in new text to change a button doesnt work.

### ISSUE THREAD

**Issue by sclient** [lemasato/POE-Trades-Companion#208]
Been a few versions now, but when I try to change the sold or thank you messages the first key I type deletes most of the entry.

**Comment by lemasato** [comment]
Can you share your logs? (They contain a dump of your settings and your AHK version, it would allow me to see if it's due to some specific settings)
\Documents\lemasato\POE Trades Companion\Logs\ zip and attach the archive.

**Comment by sclient** [comment]
[logs.zip](https://github.com/lemasato/POE-Trades-Companion/files/3020445/logs.zip)

**Comment by sclient** [comment]
Thought Id check back in if there appears to be a problem with my install.

**Comment by lemasato** [comment]
Sorry for no answer. I was sure I posted.

Actually, I think I misunderstood the issue.
Some actions need to start with a specific string, otherwise would will get a warning about it and it's content will be reset to "that specific string".


For example, the "Send to buyer" action:
It **needs** to start with `@%buyer%`
If you try to remove that part from the string, it will reset back to `@%buyer%` and tell you that this action needs to start with `@%buyer%`

In older versions, %buyer% used to be called %buyerName%.
And I think that's the cause of your issue.
Your messages are still of the old version, using %buyerName%. Therefore, when you try to edit the message, it shows you the warning (because it can't find `@%buyer%`) and resets the string.

The solution would be to let it reset your message and type in your new one.
You can use the item name and price in your message with the %item% and %price% [variables](https://github.com/lemasato/POE-Trades-Companion/wiki/How-to-use#variables).



Nevertheless, I'll push a tiny fix to allow @%buyerName% (which still works anyway) in the string.

**Comment by sclient** [comment]
Ah, ok, thanks much.. Yeah, there were other variables in the string as I recall (I was working on the thank you and sold messages), and I didnt know how to add those back in properly, so Ill be happy to see the new version (been struggling bc I added some helpful information in my sold string that is no longer relevant).

**Comment by lemasato** [comment]
Allowing other variants wouldn't have been optimal.
But upon starting the script, any "old variable" will be replaced with its "new" ones to avoid this issue from happening.

Also added a tiny message on the top of the Buttons section tab about variables.

These changes will be available in the next update.
