### ISSUE TITLE
Add a disable option for the new buying menu.

### ISSUE THREAD

**Issue by Z0MBIE2** [lemasato/POE-Trades-Companion#218]
The new menu for purchasing items is neat, but there doesn't seem to be any customization for, it and I can't disable it despite not having a use for it. Would be nice QOL if a disable button got added.

**Comment by DocHoncho** [comment]
If you're talking about the weird second window, I whole heartedly agree.  In fact, even if you're not, I agree.  More control is better!

That second window just has weird Icons with no hover so whatever they do it's a mystery until you press them all.  Bad juju.

**Comment by Z0MBIE2** [comment]
> If you're talking about the weird second window, I whole heartedly agree. In fact, even if you're not, I agree. More control is better!
> 
> That second window just has weird Icons with no hover so whatever they do it's a mystery until you press them all. Bad juju.

Yep, I am talking about it. It seems like it's a work in progress due to the missing buttons, and when I did send a PM it had it's background kind of messed up.

**Comment by lemasato** [comment]
> That second window just has weird Icons with no hover so whatever they do it's a mystery until you press them all. Bad juju.

@DocHoncho Are they?
I was thinking it would be kind of intuitive.
First toolbar icon is the hideout icon from in-game, when you click on the waypoint.
Second toolbar icon is just a L (for "League"), I agree it's confusing but I couldn't think of any suitable icon in time.

First trade icon is a double bubble, the same as the one on the "Old" interface, which allows to write to the seller.
Second is the hideout icon again, but this time in the seller window, so it hints that it should be going to the seller's hideout.
Third icon is the same as the "kick buyer" icon from the "Old" interface". Except you're buying items, and you cant kick the party owner, so it's kicking yourself.
Last icon is a thumbs up. Hinting that you're happy with the trade, which sends a "ty!" message.

![pic](https://cdn.discordapp.com/attachments/488063333719867413/586395802247626754/Preview.png)

***

And yup, this is still a work in progress. Lot of people have been asking for an interface when buying items, and so I decided, if I could, to get it ready before Legion release so that users could enjoy it.

As indicated on [1.15.BETA_2 changelog](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.15.BETA_2), I actually plan on making the new interface compatible with selling items, and give the option to choose between this new interface or the old one that uses tabs.
Though, honestly, it won't be very soon. So in the meantime, I'll just add a tray option to disable this new "buying" interface.

**Comment by lemasato** [comment]
> Yep, I am talking about it. It seems like it's a work in progress due to the missing buttons, and when I did send a PM it had it's background kind of messed up.

@Z0MBIE2 Could you provide a screenshot of it?

**Comment by Z0MBIE2** [comment]
> > Yep, I am talking about it. It seems like it's a work in progress due to the missing buttons, and when I did send a PM it had it's background kind of messed up.
> 
> @Z0MBIE2 Could you provide a screenshot of it?

[Here's a picture of it](https://i.gyazo.com/bab19e5815139e2155748f4bc59ae9f2.png)

**Comment by DocHoncho** [comment]
@lemasato While I'm completely willing to admit that "it might just be me", with regard to icons and the like, those of us who are not as "visually attuned" can have issues sorting them out.  Your explanation was reasonable, and the icons do make sense (sometimes icons are so abstract as to be nearly meaningless), having an explanation somewhere might be a good idea.  I don't know if hover text is possible with AHK, but that would be a reasonable compromise.

It's also nice to have buttons for "Ask to wait", "Still interested", etc.  Especially Ask to wait, trying to type while chasing the delve cart is asking for trouble!

**Comment by lemasato** [comment]
I'm not really sure if adding "custom buttons" to the buying interface could be any good. Majority of the time, it's all about joining the hideout, putting the currency, and leaving party with sometimes saying ty for trade or something.
Though, when "selling items" becomes available on this new compact interface, it'll have a few custom buttons for sure.

**Comment by Z0MBIE2** [comment]
I suppose I'll close this issue then as Lemasato added the suggestion, thanks!
