### ISSUE TITLE
Does not auto-update from 1.15.BETA_9 to BETA_11

### ISSUE THREAD

**Issue by MaT-PT** [lemasato/POE-Trades-Companion#237]
Hi, when trying to auto-update to the latest beta from 1.15.BETA_9, it says it’s up to date, even though it clearly states that the latest is BETA_11 (and the "Accept BETA updates?" box is checked).
I’m guessing it’s a string comparison problem (since `"1.15.BETA_11" < "1.15.BETA_9"` when doing an alphabetical string order comparison).

I will update manually, I’m just letting you know this problem exists.

Thanks for this awesome tool btw!

![PoE Trades Companion update problem](https://user-images.githubusercontent.com/551453/60465712-1419d780-9c52-11e9-8b0a-a236a968704f.png)

**EDIT:**
I tried downloading BETA_10, it updated to BETA_11 as expected. Either the problem was fixed in this version, or it’s just the string comparison that works now since `"BETA_10" < "BETA_11"`.

**Comment by lemasato** [comment]
Oops, thanks for reporting on this!
I guess I'll have to make the next beta 90, so that others are getting the update automatically.

If curious, you can see how I'm comparing versions in Updating.ahk, from line 33
https://github.com/lemasato/POE-Trades-Companion/blob/e597fcd051f00349830b87ce2ab72fc30e5537f3/lib/Updating.ahk#L33-L49

**Comment by lemasato** [comment]
Fixed as of 1.15.BETA_90, thanks for reporting!
