### ISSUE TITLE
Can't automatically update from 1.15.BETA_92 to 1.15.BETA_93 or 1.15.BETA_94

### ISSUE THREAD

**Issue by noraj** [lemasato/POE-Trades-Companion#247]
Can't automatically update from 1.15.BETA_92 to 1.15.BETA_93 or 1.15.BETA_94.

I don't know if it is due to the fix you made in https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.15.BETA_94

>  Updating would copy the whole folder instead of only its files (broken by 1.15.BETA_92).

If it is the cause maybe add a warning to tell people they need to update manually.

**Comment by lemasato** [comment]
Yeah, some bug from BETA_92.  
I made an announcement in Discord, but sadly that's all I can do :/
I'm sorry this happened, it's just stupid
![image](https://user-images.githubusercontent.com/14184969/61483402-00ce7200-a99d-11e9-9068-b3d034171cfd.png)

**Comment by noraj** [comment]
> but sadly that's all I can do :/

What about putting something in the CHANGELOG of BETA_92 so people will be able to read it from AHK Settings directly?

**Comment by lemasato** [comment]
Changelogs are read from a local file.
And the thing that's happening with this bug is that, it's downloading the new version zip, extracts it, but then copies the entire folder into your Trades Companion folder instead of its content.
So in the end, no file is being replaced at all, changelogs included. Which means I really can't do anything :/

I should think of some kind of MOTD feature, where if I edit a file on GitHub itself, users will get a notification box on application start.

**Comment by noraj** [comment]
Arf that's bad, yeah maybe grabbing the release not from github instead of a local file.
