### ISSUE TITLE
Sometimes tabs are not appearing + in tab price dot can't find my currency trades

### ISSUE THREAD

**Issue by ormarek** [lemasato/POE-Trades-Companion#256]
Tabs are not appearing for players with asian (not sure what language it is) characters in nickname.
Also 1/4 of messages i receive are not appearing as trade tab, even if message is correct.

Also when I'm trading currency dot that should show if price is correct always says that it cannot find my listing on poe.trade and is always yellow
[Logs.zip](https://github.com/lemasato/POE-Trades-Companion/files/3616414/Logs.zip)

**Comment by lemasato** [comment]
> Tabs are not appearing for players with asian (not sure what language it is) characters in nickname.
Also 1/4 of messages i receive are not appearing as trade tab, even if message is correct.

Whispers from Korean players aren't logged in Client.txt.
This is a privacy requirement from Korea, and there is nothing I can do.
https://github.com/lemasato/POE-Trades-Companion/issues/236 - [Reddit 1](https://www.reddit.com/r/pathofexile/comments/c6yijd/bug_important_korean_whispers_not_being_logged_in/) - [Reddit 2](https://www.reddit.com/r/pathofexile/comments/c93tvs/bug_important_korean_whispers_not_being_logged_in/)

> Also when I'm trading currency dot that should show if price is correct always says that it cannot find my listing on poe.trade and is always yellow

The next big update will be using Pathofexile.com/trade instead of poe.trade. Which could potentially fix this, so we'll have to wait and see until then.

**Comment by ormarek** [comment]
Didn't know about the first one, then it's okay, I will just ignore them, as it's too big mess with huge amount of trades.

Can you tell me when you estimate next "big" update?

**Comment by lemasato** [comment]
I can't. There's still some work to do.
But I'm sometimes posting updates preview on the Discord server.

**Comment by ormarek** [comment]
Okay, will join discord then. Thanks for all your work
