### ISSUE TITLE
[Suggestion] Clipboard map tab suggestion

### ISSUE THREAD

**Issue by Johay90** [lemasato/POE-Trades-Companion#266]
With the new atlas, the highlighting part can be a bit wacky (not surprising). I'm guessing highlighting each maps location isn't going to viable anymore since map locations might be all over the place with the atlas.

Would it be possible for the clipboard button to copy the base map name only? ie Superior Atoll Map would be copied to "Atoll map". It still would be good if the program still highlighted the map location once you're in the correct map tab.

Can be a little hard to find the map locations without highlighting/searching, especially when trading magic/rare/quality maps.

**Comment by lemasato** [comment]
Hi,
Sorry for delayed answer (was unavailable until now).

How is the highlighting wacky with the new atlas?
If I understand correctly, you can now change map tier completely, right?
So this would mean that a map that is normally T1 could be both in T1 and T15 tabs?

I haven't played much at all, so I don't know much about the new atlas and map stash tab interactions.

**Comment by Johay90** [comment]
Hey,

That is correct, for some maps that you unlock early they could have 5 different tiers they could be

for example Pier map (which is base Tier 1)
0 WS - Tier 1
1 WS - Tier 4
2 WS - Tier 8
3 WS - Tier 10
4 WS - Tier 14

Map positions (map tab): This is the "wacky part" I was speaking of, If let's say I don't have a "pier" tier 14 the map wouldn't show up in the map tab at tier 14, but if I do it's obviously there but might make highlighting very tricky. I believe maps only show up in the map tab at their "base tier" if you don't have a version of their 'higher tier'

For example, if I have zero piers at any tier, it would still be in the map tab at tier 1 (like it used to be), but since I don't have those other, higher tiers of this map, it wouldn't show in any of the other tabs (so if you wanted highlighting to work accurately, there literally could be 100s of "combinations" of positions depending on what current maps the player has in their tab). 

The next problem with the highlighting with the map tab is now that you could have quite a number of maps of that tier some tabs have a "[scroll bar](https://streamable.com/iitrn)".

**Comment by JusKillmeQik** [comment]
Agreed, there isn't really a way to show the map location since they can move based on what you own. Its probably best if you just highlight tier and location within the tab.

That said, the one way I could think of is if you did a control-f search and then pasted the name of the map into it. That would hightlight all of the tiers and the map within a tier. Then your boxes would show the correct tier and map to select while the game highlighting would show its location within a tier. I dont think that could be automatic, but perhaps a button press to hightlight the map within the stash tab?

**Comment by lemasato** [comment]
Hi,
An update about this was pushed a while ago. Due to the new atlas system which makes the Map Tab unpredictable, the map type location will not be shown anymore until I can work on a proper solution.

I'll be closing this issue to keep the issues tab cleaner as those are on my consider/to-do list. A page will be opened with future possible updates.
