### ISSUE TITLE
[Feature Request] Easily pick up currency when buying

### ISSUE THREAD

**Issue by MeltWS** [lemasato/POE-Trades-Companion#277]
There is a feature (stack click) that does this for currency trading, only for selling.
It would be usefull to have the same working when buying as well.

**Comment by lemasato** [comment]
Would be hard to do currently, due to how the buying interface works.
StackClick works just fine with the tabs interface system, as it shows only a single trade at a time.
The buying interface shows multiple trade at a time, and so the hotkey wouldn't have any way of knowing which currency from which trade should it take. This may change in the future, if I can make it so the user is able to "focus" a specific slot of the expanding interface.

**Comment by lemasato** [comment]
I'll be closing this issue to keep the issues tab cleaner as those are on my consider/to-do list. A page will be opened with future possible updates.
