### ISSUE TITLE
Hold CTRL bug

### ISSUE THREAD

**Issue by 0ldi** [lemasato/POE-Trades-Companion#292]
When I press ctrl+F or ctrl+V (not sure) for use stash filter and find the item, the tool tries to use this function:
![image](https://user-images.githubusercontent.com/16578229/77640806-0d638b00-6f6c-11ea-9564-66b031926c3c.png)
Prior to this, a default macro was used to invite the buyer:
![image](https://user-images.githubusercontent.com/16578229/77640850-1eac9780-6f6c-11ea-8e5a-18b8a485f9c9.png)
As a result, the tool tries to resend the invitation message and also interrupts my interaction with stash and opens Social Screen (friendlist) my bind V
As I understand it, the tool should ignore ingame CTRL press + copy, and work only on sites, but for some reason It don’t.

It appeared with me a few days ago, I don’t remember exactly after which, possibly incorrect closing of the tool is possible. Do not tell me how to fix it?

**Comment by lemasato** [comment]
Hi,

I believe this is caused by an external tool reverting the clipboard content.
Instant Whisper will be trigger if you're holding CTRL at any point when a trading whisper is copied into your clipboard. It is working at all times and doesn't specifically work only while your browser is active.

Though, I suppose that it could be changed so that it doesn't trigger while the game window is activated.

**Comment by VeldoraTempest** [comment]
Is there any way to change the Hold CTRL button to anything else ? like I need to hold shift to do the instant whisper ? Because CTRL is bugging me with the Poe live search manager which instantly copies a trade message when a live search result pop up. So whenever I am holding CTRL ingame(as I am using CTRL a lots of time ingame to transfer item from stash to inventory) it sends instant message of that live result. Is there anyway to change the CTRL button to anything else ? If I need to chnage the button myself in which file it is located ? So that I can change to CTRL button ? Thanks in advance.

**Comment by lemasato** [comment]
@VeldoraTempest As of now, the only way to change it is to manually edit files.
File: `\POE-Trades-Companion\lib\OnClipboardChange.ahk`
Line 13. Change `modKeyVK := "0x11"` to `modKeyVK := "0x10"`
This will effectively change the CTRL key to SHIFT

**Comment by VeldoraTempest** [comment]
> @VeldoraTempest As of now, the only way to change it is to manually edit files.
> File: `\POE-Trades-Companion\lib\OnClipboardChange.ahk`
> Line 13. Change `modKeyVK := "0x11"` to `modKeyVK := "0x10"`
> This will effectively change the CTRL key to SHIFT

Thank You very much
