### ISSUE TITLE
Can't add more buttons

### ISSUE THREAD

**Issue by joe7dust** [lemasato/POE-Trades-Companion#293]
We should be allowed to add tiny buttons with icon like you have built in, Clipboard, Whisper, etc.

The button size of "small" is like 5 times larger by comparison and doesn't have ability to have informative icon.

**Comment by lemasato** [comment]
Hi,

The next major update fixes this by making the interface much more compact.
Also the buttons will take space based on how many buttons there are on that row.
For example, if there are only 2 buttons on the row, each button will be 50%.

Additionally, you will be able to use pre-defined icons instead of text.
