### ISSUE TITLE
Close All

### ISSUE THREAD

**Issue by ggurman** [lemasato/POE-Trades-Companion#306]
I'd like to see a button to close all open tabs/list items (e.g., an X next to the minimize button at the top of the window).

For example, I send whispers to 5 different people for an item. I only hear from the fifth one. Currently, I have to individually close each other list item (I'm sure you have lingo for this, but I don't know it). 

Same with buy request tabs. Occasionally I'll list something at to low a price and I get a flurry of bot responses. I can use /dnd to stop getting them, but I need to individually close each tab.

I think you get the idea.

Thanks!

**Comment by lemasato** [comment]
Hi,
This can be done by right clicking the "X" button.
Then you can decide to close all tabs, or only those corresponding to the same item.

**Comment by lemasato** [comment]
Also, I'm not sure about the current BETA anymore, but on the current Discord ALPHA this is available by right clicking anywhere on the interface (instead of specifically on the "X" button)

Again, if you are interested into trying out the ALPHA, [this is the Discord invite link](https://discord.gg/UMxqtfC).

![image](https://user-images.githubusercontent.com/14184969/87829980-5ffce600-c880-11ea-9af2-5e32b8cc38fd.png)
