### ISSUE TITLE
[Feedback] I feel like this program went in the wrong direction.

### ISSUE THREAD

**Issue by humenbean** [lemasato/POE-Trades-Companion#38]
Needless to say, this program overall is a ridiculously needed for this game. And I am very thankful for it. It has easily doubled the speed I can trade at.

There are two things that really confuse me though. The 'close all tabs' option and the overlay.

First the, 'close all tabs...' contributes to one of the main issues with trading, people being rude to each other and promoting less trading overall. Five people messaged me! Better sell to the first one and tell the other 4 I don't care that they exist. I know you said you'd be adding the option to remove this, and it would be greatly appreciated, but I hope that new features moving forward are more considerate of trading as a whole. It does solve a problem where someone has 19 pms for the same item, and I get that can be frustrating, but that can easily be prevented by the user not carelessly miss pricing their items or throwing them into the wrong tabs. It's basically a band-aid for bad behavior that punishes everyone else.

Past that, I would really really like to go be able to use the old look. Trading for me isn't fun. It's even a chore sometimes with all the 1c pms. So I'd like to have a clean and easily readable interface to look at. So I can use it and get back to the game asap. I've got almost near perfect eye sight, but the new skin is much harder to read. Especially if I'm selling multiple exalts and someone uses poe.trade to up the amount and auto calculate the price.

People will and continue to try to scam you in the game. No surprise there. One of the common tricks scammers use is to modify the messages that are copied from currency.poe.trade to lower the costs of currency. 3ex for 276c! Instead of 3ex for 279c! With the old interface I could read the numbers incredibly easily. The new interface on the other hand, I constantly am hovering over the text to see the unedited text/skin cover.

Maybe it works well for people on 1080p, but at 1440p, and being in the far right top corner, goes back to the, 'trading is frustrating' argument.

A few updates ago, when there was no skin, and it didn't auto close all windows, perfect. So good. It was almost as if I didn't even know I was using the program. Well organized, clean, no bullshit, abc setup. Now it's harder to read, blends in with the game and is easily forgettable if you're in a rota, and promotes bad trading habits of blanket ignoring more than 1 person. I would go back to using an old version, but there seemed to be some important additions and fixes after that went live. I tried to undo the overlay myself, but it just comes back. I also tried to go in and mess with the preferences, but couldn't find something that allowed me to revert these two changes.

My only regret is that I wish I could offer something in return for this awesome program you made, it's way better than Mercury which, is way less intuitive, and worse for people who do a lot of trading, and hope these options will popup soon. It is an 'old guy' mentality of not wanting change, but sometimes I think honing stuff in a little, is what really makes a quality program shine.

**Comment by lemasato** [comment]
All of these listed behaviours will be fixed in the next major release!  
&nbsp;  
The message box will no longer open every time you try to close a tab that shares similar infos with another tab. Instead, the user will have to right click the X (Close) button and choose "Close similar trades".  
I wish I could make it so the user can send a message to the buyer upon automatically closing the tab, but the chat would end up blocking us from sending any further message to prevent spam.  
Of course, I could add a small delay between every message, but then if (for example) we are closing 20tabs, the user would require to wait until all tabs are closed and all messages are sent.  
Anyways, it wouldn't fit with the "One server action per hotkey" GGG Policy.  
&nbsp;  
You will be able to revert to the old GUI, as well as adding your own theme (or simply a theme made by the community) to the GUI.  
It will also allow you to scale the GUI bigger.  
&nbsp;  
Thanks a lot for your detailed review!

**Comment by humenbean** [comment]
Sounds awesome, really looking forward to it. If you need anyone to do testing let me know. Some days I just sit around for a few hours flipping currency.

**Comment by lemasato** [comment]
Hello there!  
The classic interface is back with the 1.9 update.  
You can also scale the interface bigger (from 50% to 200%).  

Thanks again for the feedback!
