### ISSUE TITLE
Running without admin

### ISSUE THREAD

**Issue by Kache** [lemasato/POE-Trades-Companion#51]
I would like to have the option to just run without admin. I currently start, deny, start, deny, start, run w/o admin.

I tried running the standalone ahk script with [`Run_As_Admin()`](https://github.com/lemasato/POE-Trades-Companion/blob/master/POE%20Trades%20Companion.ahk#L112) commented out, but the script is unable to find `Resources/AHK/BinaryEncodingDecoding.ahk`, which seems to be missing from the repo.

**Comment by lemasato** [comment]
I could add a Command-Line Parameter for this.
But what's the point of running without admin rights? In this mode, the main interface's buttons are unable to send in-game messages.

**Comment by Kache** [comment]
I don't know why, but it still works for me. The same is true for the POE TradeMacro, which used to include a "No Admin Elevation" version, which always worked for me. When that stop being provided, all I had to do was get the source and comment out admin escalation.

I'd be fine with being able to run Companion in the same way, which led me to discover that one particular file to be missing from the Github repo.

**Comment by lemasato** [comment]
I just tested, and it seems to be working fine without admin privileges.
Strange... Last time I tried, it would be unable to activate the game's window to send the message.
That version was probably still using ControlSend instead of WinActivate & SendInput.

The BinaryEncodingDecoding.ahk file being omitted is nothing more than a mistake of mine (It has no use currently). You can still find the file on the [dev branch](https://github.com/lemasato/POE-Trades-Companion/tree/dev/Resources/AHK).

**Comment by Kache** [comment]
Cool, thanks. I wasn't able to get the `.ahk` file from the dev branch running properly (the GUI displays non-functional A, B, and C buttons for the first row), so I'll just wait for the next release.

**Comment by lemasato** [comment]
If you wish, you can download the compiled beta executable [right there](https://github.com/lemasato/POE-Trades-Companion/raw/dev/POE%20Trades%20Companion%20(Beta).exe).

**Comment by lemasato** [comment]
This feature has been added as 1.10.
To make it easier, a shortcut will automatically be created upon failing to run as admin, then launching the executable again. I'll be leaving this open for a while, in case you have any question.
