### ISSUE TITLE
"될×囹矈둘×" file created when launching Trades Companion

### ISSUE THREAD

**Issue by rushtothesun** [lemasato/POE-Trades-Companion#68]
I was just curious what this file is. I'm using BETA_8.

**Comment by lemasato** [comment]
Add .txt as extension to the file and tell me the content, if you don't mind.
Sounds like the local file issue again

**Comment by rushtothesun** [comment]
It says [PROGRAM] inside

**Comment by lemasato** [comment]
Checked all IniWrite making use of the PROGRAM section, and found the culprit.

As of the performance hit, I haven't noticed any on my end.  
Compared BETA_8 with BETA_3 and BETA_7, and they all seem to have the same speed. But on the next BETA, I'll probably make use of the clipboard, which should be faster for long messages.

It's strange to see that deleting the folder resolved your issue, but that's good to know.
I'll have to inspect on that part.

**Comment by lemasato** [comment]
Hi there,
Fixed as of [1.12.BETA_10](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.12.BETA_10).

>A file using some weird characters could appear in the folder you are running the application from.
If you happen to have this file, it can safely be deleted.
The origin of this file was due to an invalid path to the local .ini file, which would result in the location defaulting to the tool's folder.
Also, if in the future this issue re-appear, the file will be placed in the application's local folder instead (\My Documents\Autohotkey\POE Trades Companion), in order to avoid any trouble.

Thank you for reporting!
