### ISSUE TITLE
QoL - Special Hotkey for sending the modulo of the item's stack size for easy un-stacking.

### ISSUE THREAD

**Issue by Megaddd** [lemasato/POE-Trades-Companion#80]
Best explained in the following example:
Item count = http://i.imgur.com/g6UAcOo.png

Take the item count, and get the modulo of the item/currency stack size, to get the final stack split amount.
Then simulate a keystroke for the number returned.

Example usage scenario:
Someone's buying 29 vaal orbs.
I ctrl+click twice to get 20, then shift+click and press the 'Special Hotkey' to type in 9 for me.

**Comment by lemasato** [comment]
Nice. I'll consider it.
Even better, we could handle the ctrl+click internally based on the currency max stack count.

How it could work:
When doing a ctrl+click in game, the tool check the item data (using ctrl+c). If it matches the current tab's currency, we use ctrl+click as many as we need to get the get the currency then shift+click to get the remaining. It it doesn't, simply process the ctrl+click keystroke normally.

**Comment by Megaddd** [comment]
perhaps as a ctrl+shift+click, as sometimes ctrl+clicks get dropped by the server from clicking excessively.

**Comment by lemasato** [comment]
Ctrl+Shift+Click? It behaves just like a shift+click to me, or am I missing something?  
Just tested out and yep, some Ctrl+Click are dropped when going too fast, wasn't aware.

Adding a 100ms delay between clicks seems to work just fine, but then again it cannot perfect.
If a fps lag were to happen during the function (due to a buyer with too many fancy effects entering your area, or any exterior source), the inputs would not be picked up by the game.

I guess emptying the clipboard then using Ctrl+C before doing the next click would be nice.
If the clipboard is still empty, that means the client is not responding.

**Comment by Megaddd** [comment]
The idea behind ctrl+shift+click is that it will not override the actions of ctrl+click or shift+click, it's an unused keybind to put ^+click on

**Comment by lemasato** [comment]
Oh yeah. That'd be actually better.

Their state is "One server action per macro".
But honestly, it would be so much of a QoL change for currency traders.
At this point, I don't even know what should be done...

**Comment by Megaddd** [comment]
Just an unstack key is more than enough, as typing 14, 12, 9, 7 is the biggest pain in the ass when currency trading 😃

**Comment by ldbenoit** [comment]
This is a great idea. I think to get around the TOS it should operate as follows.


CTRL+SHIFT+Click On Item
Trade companion checks if it's the proper item / if not just ctrl+click
Check if the amount is more than one stack / if not, shift+click and enter amount
Ctrl+Click and either add to a tally of amount withdrawn or subtract from the total needed

I could see spam clicking being a problem. I would have it play a sound and maybe add a delay after you've withdrawn enough.

Let me know if you are too busy for this, I could work on it while I'm awaiting my RMA card.

**Comment by Megaddd** [comment]
I believe the manually clicked auto unstacking is the way to go, because it allows the player to account for lantency issues (wait for the currency to move), and abide to ToS.

**Comment by ldbenoit** [comment]
I worked on this this morning and it is pretty darn nice. I suppose a simple modulo could be almost as handy. Try it out and let me know what you think. Right now it won't let you take out more than the required amount, I'm not sure if thats the best way of handling it.
https://github.com/ldbenoit/POE-Trades-Helper/commit/cdbe6d0afbdb1e93c9ffaf5804402372467839ac
The paths for the two currency files were incorrect so that should be fixed either way.

**Comment by lemasato** [comment]
This functionality will be part of the next BETA release.

**Comment by lemasato** [comment]
This is now core of the tool, as of [1.12.BETA_12](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.12.BETA_12).
Try it out, and feel free to give your opinion!

**Comment by Megaddd** [comment]
Sorry I hope you took the silence as the best compliment, haha. 
Works great!

**Comment by lemasato** [comment]
No worries, all good :p
Happy trading, thank you for bringing this suggestion!
