### ISSUE TITLE
"Send message" to local only

### ISSUE THREAD

**Issue by Petax** [lemasato/POE-Trades-Companion#88]
Hello.

Maybe I'm stupid but the message sent always just sends to Local chat. Even though I confirmed the message contains the correct syntax, i.e. @%buyerName% first

**Comment by damoochie** [comment]
Noticed this also... you're not stupid :p

**Comment by lemasato** [comment]
Does it always happen?  
Can you confirm happens for both hotkeys and custom messages?

**Comment by Petax** [comment]
Yes it does. I have noticed typing @ on my computer has a bit of a delay to it as of recently. Maybe that has something to do with it.

**Comment by Petax** [comment]
I found a solution. Some ASUS software was blocking the inputs and delaying the key presses. Disabled the softwares key bindings and now it works as before.

**Comment by lemasato** [comment]
@damoochie Could you make sure you are not using any that could potentially interfere with this tool? (Clipboard manager, keyboard tools, ...)

**Comment by Petax** [comment]
Yeah read my reply above. Solved it.

**Comment by damoochie** [comment]
The only other 'tool' I use is TradeMacro/ItemInfo.

But I started using the Beta version of TC and it now only happens on rare occasions.

I did get the bug of an item occasionally being posted locally instead of replying with what was setup via customisation... i think i saw this reported elsewhere though.

I also noticed the chat box appearing and disappearing as the commands are input into the console... the last stable version was instant. Could this delayed input be causing issues?
-- I am not a programmer so just throwing it out there xD --

**Comment by lemasato** [comment]
@damoochie Yup, it's been reported over #87 and on the forums.  
The way messages are sent is different on 1.12.x. Previously, people could get kicked for "performing too many actions too fast". So now, instead of "pressing each key", we make use of the clipboard.  
The small delays are to make sure the message is being sent correctly.

I'm not sure if it's an issue with the game itself or TradeMacro.
When I'd have the issue, restarting the game would fix it instantly.

**Comment by damoochie** [comment]
I see... makes sense. Thanks for the info.

**Comment by lemasato** [comment]
@damoochie If you happen to get the "item being posted locally" thing on 1.12, please let me know.

**Comment by damoochie** [comment]
Everything seems to be working smooth now!
