### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by Krzysiu** [lemasato/POE-Trades-Companion#96]
Hey! For now I'm going to write effect, you tell me what more info you need.

The problem is that when POE Trades Companion is running, the performance of game is much worse. I've tried both overlay and window mode. When POE is running, the FPS meter in windowed fullscreen game goes from ~40 to ~15 FPS, in fullscreen mode I've got 10 FPS drop (from 50). I'm using Direct 9ex. It happens on every machine I've used. I'm using Windows 7 and POE is ran thought Steam. CPU usage of POETC is rather high. When it's inactive, it takes about ~0.1% of so-called "CPU usage", which is more than currently running web browser full of active tabs and addons, but I don't think that CPU itself is a problem - it's rather badly optimized. The FPS drop issue seems to be something else. I've tried fresh copies and it's the same.

**Comment by lemasato** [comment]
Hi there,
I remember someone complaining about FPS drops on the forums, but sadly never got any feedback about it. It could be related to your protection flagging the tool as harmful. See if using the AHK source helps.  

The only things the tool do in the background are:
- Monitoring your chat logs.
Client.txt is scanned for new lines every 200ms so that the GUI notification doesn't appear too delayed. This value is increased to 400ms if no trading whisper has been received within the last 5mins and to 600ms after an hour. Though, this should have no impact performance wise.
- Show tooltips when your move hovers a slot from the Trades GUI (main interface), in case the item's name was too big and had to be trimmed. But this only occurs while the mouse is effectively on the GUI. There was an issue related to this which would cause a cpu usage spike when moving the mouse, but it has been fixed long ago (and to be honest, wouldn't have been noticed by most users as you don't usually move around your mouse in circles inside the GUI just to see the CPU usage increase).
- Check for updates every 140 minutes. This is in case the user never turns off his computer or always leave the application running.

I personally don't notice any fps change with or without the tool, and you definitely shouldn't either.  
But in case you do, in my opinion, it could be possibly related to something external.  

Either way, if you still get FPS drops while using the AHK source try this:
POE Trades Companion.ahk: At line 725, change `SetTimer,% A_ThisFunc, -%timer%` to `; SetTimer,% A_ThisFunc, -%timer%` and run the file. If you don't get performance hits anymore after that, see if changing `SetTimer,% A_ThisFunc, -%timer%` to `SetTimer,% A_ThisFunc, -1000` helps.

**Comment by Mith223** [comment]
Hi, I had a similar problem. I decided to do it this way: initially, my Windows 7 was personalized in a simplified mode, but putting Aero FPS drops were removed
